server:
  port: 0 # 랜덤포트

spring:
  application:
    name: user-service

eureka:
  instance:
    # instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}} # 랜덤포트로 실행되면 인스턴스가 하나밖에 안보이는데, 인스턴스별로 따로 보기 위함 (IP)
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Application name
  client:
    register-with-eureks: true
    fetch-registry: true # EUREKA 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지에 대한 설정, true로 설정하면 갱신된 정보를 받겠다는 의미
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # 이 서버에 마이크로서비스를 등록하겠다는 의미

greeting:
  message: Let's use yml args